"""add user profile photo key

Revision ID: af3233085cc3
Revises: 6686d202d8f4
Create Date: 2026-09-07 12:05:09.755066
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "af3233085cc3"
down_revision: str | None = "6686d202d8f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("picture_key", sa.String(length=64), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "picture_key")
    # ### end Alembic commands ###
